spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:8151/football
    driverClassName: org.mariadb.jdbc.Driver
    username: football
    password: football
    hikari:
      pool-name: football-db-pool
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 6000
  application:
    name: football
